"""
complex_generator.py
Generates a full Registan-style madrasa complex:

  Three buildings arranged in a U-shape around a central courtyard,
  mirroring the historic Registan of Samarkand (Ulugh Beg, Tilya-Kori, Sher-Dor).

Layout (top-down, Y+ = north):
  ┌──────────────────────────────┐
  │       [NORTH BUILDING]       │  ← Tilya-Kori style (wider, flatter dome)
  │                              │
  │  [WEST]    [PLAZA]   [EAST]  │  ← Ulugh Beg / Sher-Dor style (tall minarets)
  │                              │
  └──────────────────────────────┘

Each building is generated by calling the same individual generators,
but with per-building parameter overrides layered on top of a shared base.
"""

import bpy
import sys, os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ..generators.base_building import generate_base
from ..generators.dome import generate_dome
from ..generators.minaret import generate_minarets
from ..generators.arch import generate_arches
from ..generators.courtyard import generate_courtyard
from ..generators.muqarnas import generate_muqarnas
from ..utils.material_utils import assign_material
from ..utils.tile_material import apply_tile_materials_to_collection


COMPLEX_COLLECTION = "Registan_Complex"
BUILDING_COLLECTIONS = ["Complex_West", "Complex_North", "Complex_East"]


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def generate_complex(base_p: dict):
    """
    Generate a three-building madrasa complex using base_p as the template.

    Objects go into sub-collections of COMPLEX_COLLECTION.
    base_p must contain all normal generator keys plus:
        complex_spacing   float  — gap between buildings (default: building_width * 1.2)
        complex_apply_tiles bool — auto-apply tile materials after build
    """
    root_col = _get_or_create_collection(COMPLEX_COLLECTION)
    _clear_collection(root_col)

    bw = base_p["width"]
    bd = base_p["depth"]
    spacing = base_p.get("complex_spacing", bw * 1.1)

    # --- Building parameter overrides ---
    # West  (Ulugh Beg): tall minarets, 1 arch, standard dome
    west_p = _override(base_p, {
        "offset_x": -(bw + spacing),
        "offset_y": 0.0,
        "minaret_count": 2,
        "minaret_height": base_p["height"] + base_p["dome_size"] * 2.0,
        "arch_count": 1,
        "arch_height": base_p["arch_height"],
        "dome_size": base_p["dome_size"] * 0.95,
    })

    # North (Tilya-Kori): wider, lower dome, 3 arches, no minarets on sides
    north_p = _override(base_p, {
        "offset_x": 0.0,
        "offset_y": bd + spacing,
        "building_width": bw * 1.4,
        "building_height": base_p["height"] * 0.85,
        "dome_size": base_p["dome_size"] * 1.15,
        "dome_segments": base_p["dome_segments"] + 4,
        "minaret_count": 4,
        "arch_count": 3,
        "arch_width": base_p["arch_width"] * 0.75,
    })

    # East  (Sher-Dor): mirror of West, slightly taller minarets
    east_p = _override(base_p, {
        "offset_x": bw + spacing,
        "offset_y": 0.0,
        "minaret_count": 2,
        "minaret_height": base_p["height"] + base_p["dome_size"] * 2.2,
        "arch_count": 1,
        "dome_size": base_p["dome_size"] * 0.95,
    })

    configs = [
        ("Complex_West",  west_p),
        ("Complex_North", north_p),
        ("Complex_East",  east_p),
    ]

    for col_name, p in configs:
        col = _get_or_create_collection(col_name)
        _clear_collection(col)
        # Link sub-collection under root
        if col_name not in [c.name for c in root_col.children]:
            root_col.children.link(col)
        p["collection"] = col
        _build_one(p)

    # Central plaza ground slab
    _add_plaza(root_col, bw, bd, spacing)

    if base_p.get("complex_apply_tiles", False):
        for col_name in BUILDING_COLLECTIONS:
            if col_name in bpy.data.collections:
                apply_tile_materials_to_collection(bpy.data.collections[col_name])


def clear_complex():
    if COMPLEX_COLLECTION in bpy.data.collections:
        root = bpy.data.collections[COMPLEX_COLLECTION]
        for child in list(root.children):
            _clear_collection(child)
        _clear_collection(root)


# ---------------------------------------------------------------------------
# Internal: single building
# ---------------------------------------------------------------------------

def _build_one(p: dict):
    ox = p.get("offset_x", 0.0)
    oy = p.get("offset_y", 0.0)

    objects_before = set(p["collection"].objects)

    generate_base(p)
    generate_dome(p)
    generate_minarets(p)

    if p.get("balcony_enabled", False):
        try:
            from generators.balcony import generate_balconies
            generate_balconies(p)
        except Exception:
            pass

    generate_arches(p)
    if p.get("muqarnas_enabled", False):
        generate_muqarnas(p)

    if p.get("iwan_enabled", False):
        try:
            from generators.iwan import generate_iwan
            p["iwan_depth"] = p["arch_width"] * p.get("iwan_depth_factor", 1.8)
            generate_iwan(p)
        except Exception:
            pass

    if p.get("arcade_enabled", False):
        try:
            from generators.arcade import generate_arcade
            p["arcade_height"] = p["height"] * p.get("arcade_height_factor", 0.68)
            generate_arcade(p)
        except Exception:
            pass

    objects_after = set(p["collection"].objects)
    new_objects = objects_after - objects_before
    for obj in new_objects:
        obj.location.x += ox
        obj.location.y += oy


# ---------------------------------------------------------------------------
# Plaza
# ---------------------------------------------------------------------------

def _add_plaza(col, bw, bd, spacing):
    """Add a central stone plaza between the three buildings."""
    import bmesh
    from mathutils import Vector

    plaza_w = bw + spacing * 2
    plaza_d = bd + spacing

    mesh = bpy.data.meshes.new("plaza_mesh")
    obj = bpy.data.objects.new("Complex_Plaza", mesh)
    col.objects.link(obj)

    bm = bmesh.new()
    hw, hd = plaza_w / 2, plaza_d / 2
    verts = [
        bm.verts.new(Vector((-hw, -hd, -0.05))),
        bm.verts.new(Vector(( hw, -hd, -0.05))),
        bm.verts.new(Vector(( hw,  hd + bd + spacing, -0.05))),
        bm.verts.new(Vector((-hw,  hd + bd + spacing, -0.05))),
    ]
    bm.faces.new(verts)
    bm.to_mesh(mesh)
    bm.free()
    mesh.update()
    assign_material(obj, "sand")


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _override(base: dict, overrides: dict) -> dict:
    p = dict(base)
    p.update(overrides)
    return p


def _get_or_create_collection(name: str) -> bpy.types.Collection:
    if name in bpy.data.collections:
        return bpy.data.collections[name]
    col = bpy.data.collections.new(name)
    bpy.context.scene.collection.children.link(col)
    return col


def _clear_collection(col: bpy.types.Collection):
    for obj in list(col.objects):
        bpy.data.objects.remove(obj, do_unlink=True)
